tests: update status-keycard
The applet now depends on an external pre-compiled library.

Fixes the following CI failure:
```
2026-06-13T12:36:06.430076900Z main ERROR Caught exception!
java.lang.RuntimeException: Import resolution failed! Use the --jar option to add the corresponding JAR file with imports.
	at jcprofiler.instrumentation.Instrumenter.buildModel(Instrumenter.java:129)
	at jcprofiler.instrumentation.Instrumenter.addMissingClasses(Instrumenter.java:175)
	at jcprofiler.instrumentation.Instrumenter.process(Instrumenter.java:64)
	at jcprofiler.JCProfiler.run(JCProfiler.java:51)
	at jcprofiler.Main.main(Main.java:77)
Caused by: spoon.compiler.ModelBuildingException: BigNumberMath cannot be resolved to a type at D:\a\JCProfilerNext\JCProfilerNext\tests\status-keycard_im.status.keycard.CashApplet_ctor_hufvg038\sources_original\java\im\status\keycard\SECP256k1.java:140
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:649)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:631)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:118)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
	at spoon.Launcher.buildModel(Launcher.java:781)
	at jcprofiler.instrumentation.Instrumenter.buildModel(Instrumenter.java:124)
	... 4 more
```

Related: https://github.com/keycard-tech/status-keycard/commit/1a1fa0409d737a18406a683b1f1826c37ee2ad0a